export const oracleSqlIdCheckCatalog = [
  { id: "history", label: "History", phase: "Workload", source: "AWR · Diagnostics Pack", guidance: "Compare seven-day executions, plan hashes, elapsed time, CPU, reads and rows by snapshot." },
  { id: "ash", label: "ASH", phase: "Workload", source: "ASH · Diagnostics Pack", guidance: "Sample recent sessions, waits, modules, actions, plan lines and execution plans for this SQL_ID." },
  { id: "alertlog", label: "Alert log", phase: "Correlation", source: "ADR diagnostic view", guidance: "Correlate recent database warnings and errors with the statement investigation window." },
  { id: "remaining", label: "Remaining time", phase: "Runtime", source: "GV$SESSION_LONGOPS", guidance: "Estimate remaining work for currently instrumented long operations." },
  { id: "progress", label: "Progress", phase: "Runtime", source: "GV$SQL_MONITOR", guidance: "Inspect monitored execution status, elapsed time, CPU, I/O and current plan line." },
  { id: "globalStats", label: "Global stats", phase: "Workload", source: "GV$SQL", guidance: "Aggregate cursor statistics across RAC instances and plan hashes." },
  { id: "partitionNoStats", label: "Partition no stats?", phase: "Optimizer", source: "DBA_TAB_STATISTICS", guidance: "Find referenced table partitions that have never been analyzed." },
  { id: "partitionStaleStats", label: "Partition stale stats?", phase: "Optimizer", source: "DBA_TAB_STATISTICS", guidance: "Find referenced partitions marked with stale optimizer statistics." },
  { id: "sqlMonitorReport", label: "SQL Monitor report", phase: "Runtime", source: "DBMS_SQLTUNE · Tuning Pack", guidance: "Generate the authorized text SQL Monitor report for live execution detail." },
  { id: "fullOutput", label: "Full output", phase: "Cursor", source: "GV$SQL", guidance: "Return SQL text and per-child workload statistics from all instances." },
  { id: "dbInfo", label: "DB info", phase: "Context", source: "V$DATABASE / GV$INSTANCE", guidance: "Capture database, instance, version, role, open mode and startup context." },
  { id: "blocking", label: "Blocking", phase: "Runtime", source: "GV$SESSION", guidance: "Find sessions executing the SQL_ID and any current blocker chain." },
  { id: "parallel", label: "Parallel", phase: "Parallel", source: "GV$PX_SESSION", guidance: "Map query coordinator and parallel execution server membership." },
  { id: "parallelInfo", label: "Parallel info", phase: "Parallel", source: "GV$SQL_MONITOR", guidance: "Compare requested, allocated and maximum DOP for monitored executions." },
  { id: "timeBySlaves", label: "Time by slaves", phase: "Parallel", source: "GV$ACTIVE_SESSION_HISTORY", guidance: "Compare ASH sample time across coordinator and parallel execution sessions." },
  { id: "shared", label: "Shared?", phase: "Cursor", source: "GV$SQL_SHARED_CURSOR", guidance: "Review child cursor sharing failures including bind, optimizer and statistics mismatches." },
  { id: "plan", label: "Plan", phase: "Optimizer", source: "DBMS_XPLAN", guidance: "Display cursor plans with runtime rows, predicates, binds, outline, partition and parallel evidence." },
  { id: "binds", label: "Binds", phase: "Cursor", source: "GV$SQL_BIND_CAPTURE", guidance: "Inspect captured bind names, types, positions and recent values." },
  { id: "undo", label: "Undo?", phase: "Runtime", source: "GV$TRANSACTION", guidance: "Measure active undo blocks and records for sessions executing the SQL_ID." },
  { id: "wait", label: "Wait?", phase: "Runtime", source: "GV$SESSION", guidance: "Inspect current non-idle waits, state, blocker, module and execution start." },
  { id: "currentLine", label: "Current line", phase: "Runtime", source: "GV$SQL_MONITOR", guidance: "Locate the current monitored execution plan operation and line." },
  { id: "ioLatency", label: "I/O latency", phase: "Storage", source: "GV$ACTIVE_SESSION_HISTORY", guidance: "Aggregate recent User I/O wait samples and average wait time." },
];

export function oracleSqlIdCheckSql(check, identifier) {
  const sqlId = String(identifier || "").trim().toLowerCase();
  if (!/^[a-z0-9]{13}$/.test(sqlId)) throw new Error("Enter a valid 13-character Oracle SQL_ID");
  const sql = {
    history: `select to_char(sn.begin_interval_time,'YYYY-MM-DD HH24:MI') begin_time, st.instance_number inst_id, st.plan_hash_value, st.executions_delta executions, round(st.elapsed_time_delta/1e6,3) elapsed_seconds, round(st.cpu_time_delta/1e6,3) cpu_seconds, st.buffer_gets_delta buffer_gets, st.disk_reads_delta disk_reads, st.rows_processed_delta rows_processed, case when st.executions_delta>0 and st.elapsed_time_delta/st.executions_delta>1000000 then 'XRAY_SLOW_AVG' else 'OK' end signal from dba_hist_sqlstat st join dba_hist_snapshot sn on sn.dbid=st.dbid and sn.instance_number=st.instance_number and sn.snap_id=st.snap_id where st.sql_id='${sqlId}' and sn.begin_interval_time>sysdate-7 order by sn.begin_interval_time desc fetch first 100 rows only`,
    ash: `select to_char(sample_time,'YYYY-MM-DD HH24:MI:SS') sample_time, inst_id, session_id, session_serial#, session_state, wait_class, event, sql_plan_hash_value, sql_plan_line_id, module, action, case when session_state='WAITING' and nvl(wait_class,'Idle')<>'Idle' then 'XRAY_WAIT_SAMPLE' else 'ON_CPU' end signal from gv$active_session_history where sql_id='${sqlId}' and sample_time>systimestamp-interval '1' hour order by sample_time desc fetch first 200 rows only`,
    alertlog: `select to_char(originating_timestamp,'YYYY-MM-DD HH24:MI:SS.FF3') event_time, instance_id inst_id, message_type, component_id, message_text, case when message_type in (1,2) then 'XRAY_ALERT' else 'INFO' end signal from v$diag_alert_ext where originating_timestamp>systimestamp-interval '30' minute and (lower(message_text) like '%${sqlId}%' or message_type in (1,2)) order by originating_timestamp desc fetch first 100 rows only`,
    remaining: `select inst_id, sid, serial#, opname, target, sofar, totalwork, units, elapsed_seconds, time_remaining, round(100*sofar/nullif(totalwork,0),2) percent_complete, message, case when time_remaining>300 then 'XRAY_LONG_REMAINING' else 'OK' end signal from gv$session_longops where sql_id='${sqlId}' and totalwork>0 and sofar<totalwork order by time_remaining desc`,
    progress: `select inst_id, sid, session_serial#, sql_exec_id, to_char(sql_exec_start,'YYYY-MM-DD HH24:MI:SS') sql_exec_start, status, round(elapsed_time/1e6,3) elapsed_seconds, round(cpu_time/1e6,3) cpu_seconds, buffer_gets, disk_reads, physical_read_requests, sql_plan_hash_value, sql_plan_line_id, sql_plan_operation, sql_plan_options, case when status like '%ERROR%' then 'XRAY_MONITOR_ERROR' when elapsed_time>300000000 then 'XRAY_LONG_RUNNING' else 'OK' end signal from gv$sql_monitor where sql_id='${sqlId}' order by sql_exec_start desc fetch first 50 rows only`,
    globalStats: `select inst_id, plan_hash_value, count(*) child_cursors, sum(executions) executions, round(sum(elapsed_time)/1e6,3) elapsed_seconds, round(sum(cpu_time)/1e6,3) cpu_seconds, sum(buffer_gets) buffer_gets, sum(disk_reads) disk_reads, sum(rows_processed) rows_processed, max(last_active_time) last_active_time, case when sum(executions)>0 and sum(elapsed_time)/sum(executions)>1000000 then 'XRAY_SLOW_AVG' else 'OK' end signal from gv$sql where sql_id='${sqlId}' group by inst_id,plan_hash_value order by elapsed_seconds desc`,
    partitionNoStats: `select s.owner, s.table_name, s.partition_name, s.num_rows, s.last_analyzed, 'XRAY_NO_STATS' signal from dba_tab_statistics s where s.object_type='PARTITION' and s.last_analyzed is null and (s.owner,s.table_name) in (select distinct object_owner,object_name from gv$sql_plan where sql_id='${sqlId}' and object_owner is not null and object_name is not null) order by s.owner,s.table_name,s.partition_name fetch first 200 rows only`,
    partitionStaleStats: `select s.owner, s.table_name, s.partition_name, s.num_rows, s.last_analyzed, s.stale_stats, 'XRAY_STALE_STATS' signal from dba_tab_statistics s where s.object_type='PARTITION' and s.stale_stats='YES' and (s.owner,s.table_name) in (select distinct object_owner,object_name from gv$sql_plan where sql_id='${sqlId}' and object_owner is not null and object_name is not null) order by s.owner,s.table_name,s.partition_name fetch first 200 rows only`,
    sqlMonitorReport: `select dbms_sqltune.report_sql_monitor(sql_id=>'${sqlId}',type=>'TEXT',report_level=>'ALL') sql_monitor_report from dual`,
    fullOutput: `select inst_id, child_number, plan_hash_value, parsing_schema_name, module, action, executions, loads, invalidations, parse_calls, buffer_gets, disk_reads, rows_processed, round(elapsed_time/1e6,3) elapsed_seconds, round(cpu_time/1e6,3) cpu_seconds, last_active_time, dbms_lob.substr(sql_fulltext,4000,1) sql_text, case when executions>0 and elapsed_time/executions>1000000 then 'XRAY_SLOW_AVG' else 'OK' end signal from gv$sql where sql_id='${sqlId}' order by last_active_time desc`,
    dbInfo: `select d.name database_name, d.db_unique_name, d.database_role, d.open_mode, d.log_mode, i.inst_id, i.instance_name, i.host_name, i.version, i.status, i.startup_time from v$database d cross join gv$instance i order by i.inst_id`,
    blocking: `select s.inst_id, s.sid, s.serial#, s.username, s.status, s.sql_id, s.prev_sql_id, s.blocking_instance, s.blocking_session, s.final_blocking_instance, s.final_blocking_session, s.event, s.wait_class, s.seconds_in_wait, s.module, s.action, case when s.blocking_session is not null then 'XRAY_BLOCKED_SESSION' else 'OK' end signal from gv$session s where s.sql_id='${sqlId}' or s.prev_sql_id='${sqlId}' or s.sid in (select blocking_session from gv$session where sql_id='${sqlId}' and blocking_session is not null) order by s.seconds_in_wait desc`,
    parallel: `select px.inst_id, px.qcsid coordinator_sid, px.qcserial# coordinator_serial, px.sid slave_sid, px.serial# slave_serial, px.server_group, px.server_set, px.server#, px.degree, px.req_degree, s.status, s.event, s.wait_class from gv$px_session px join gv$session s on s.inst_id=px.inst_id and s.sid=px.sid and s.serial#=px.serial# where s.sql_id='${sqlId}' or s.prev_sql_id='${sqlId}' order by px.qcsid,px.server_group,px.server_set,px.server#`,
    parallelInfo: `select inst_id, sid, sql_exec_id, sql_plan_hash_value, status, px_maxdop, px_servers_requested, px_servers_allocated, round(elapsed_time/1e6,3) elapsed_seconds, case when px_servers_requested>px_servers_allocated then 'XRAY_PX_DOWNGRADE' else 'OK' end signal from gv$sql_monitor where sql_id='${sqlId}' and px_servers_requested is not null order by sql_exec_start desc fetch first 50 rows only`,
    timeBySlaves: `select qc_instance_id, qc_session_id, inst_id, session_id, session_serial#, session_state, wait_class, event, count(*) ash_samples, round(count(*)*10,1) estimated_active_seconds, case when session_state='WAITING' and nvl(wait_class,'Idle')<>'Idle' then 'XRAY_PX_WAIT' else 'OK' end signal from gv$active_session_history where sql_id='${sqlId}' and sample_time>systimestamp-interval '1' hour and qc_session_id is not null group by qc_instance_id,qc_session_id,inst_id,session_id,session_serial#,session_state,wait_class,event order by ash_samples desc`,
    shared: `select inst_id, child_number, unbound_cursor, sql_type_mismatch, optimizer_mismatch, outline_mismatch, stats_row_mismatch, literal_mismatch, bind_mismatch, user_bind_peek_mismatch, case when unbound_cursor='Y' or sql_type_mismatch='Y' or optimizer_mismatch='Y' or outline_mismatch='Y' or stats_row_mismatch='Y' or literal_mismatch='Y' or bind_mismatch='Y' or user_bind_peek_mismatch='Y' then 'XRAY_SHARED_MISMATCH' else 'OK' end signal from gv$sql_shared_cursor where sql_id='${sqlId}' order by inst_id,child_number`,
    plan: `select * from table(dbms_xplan.display_cursor('${sqlId}',null,'ALLSTATS LAST +PEEKED_BINDS +OUTLINE +PREDICATE +PARTITION +PARALLEL'))`,
    binds: `select inst_id, child_number, name, position, datatype_string, precision, scale, max_length, was_captured, last_captured, value_string from gv$sql_bind_capture where sql_id='${sqlId}' order by inst_id,child_number,position`,
    undo: `select s.inst_id, s.sid, s.serial#, s.username, t.start_time, t.status, t.used_ublk undo_blocks, t.used_urec undo_records, t.log_io, t.phy_io, t.cr_get, t.cr_change, case when t.used_ublk>10000 then 'XRAY_HIGH_UNDO' else 'OK' end signal from gv$transaction t join gv$session s on s.inst_id=t.inst_id and s.taddr=t.addr where s.sql_id='${sqlId}' or s.prev_sql_id='${sqlId}' order by t.used_ublk desc`,
    wait: `select inst_id, sid, serial#, status, state, event, wait_class, seconds_in_wait, blocking_instance, blocking_session, sql_exec_id, sql_exec_start, module, action, case when state='WAITING' and nvl(wait_class,'Idle')<>'Idle' then 'XRAY_WAITING' else 'ON_CPU' end signal from gv$session where sql_id='${sqlId}' or prev_sql_id='${sqlId}' order by seconds_in_wait desc`,
    currentLine: `select inst_id, sid, session_serial#, sql_exec_id, status, sql_plan_hash_value, sql_plan_line_id, sql_plan_operation, sql_plan_options, to_char(sql_exec_start,'YYYY-MM-DD HH24:MI:SS') sql_exec_start, to_char(last_refresh_time,'YYYY-MM-DD HH24:MI:SS') last_refresh_time from gv$sql_monitor where sql_id='${sqlId}' and status='EXECUTING' order by last_refresh_time desc`,
    ioLatency: `select inst_id, event, wait_class, count(*) wait_samples, round(sum(time_waited)/1e6,3) total_wait_seconds, round(avg(time_waited)/1000,3) average_wait_ms, max(current_obj#) current_object_id, case when avg(time_waited)/1000>20 then 'XRAY_HIGH_IO_LATENCY' else 'OK' end signal from gv$active_session_history where sql_id='${sqlId}' and sample_time>systimestamp-interval '1' hour and wait_class='User I/O' group by inst_id,event,wait_class order by total_wait_seconds desc`,
  }[check];
  if (!sql || !oracleSqlIdCheckCatalog.some((item) => item.id === check)) throw new Error("Select an approved Oracle SQL_ID investigation check");
  return sql;
}

export function analyzeOracleSqlIdCheck(check, output) {
  const definition = oracleSqlIdCheckCatalog.find((item) => item.id === check);
  if (!definition) throw new Error("Select an approved Oracle SQL_ID investigation check");
  const text = String(output || "");
  const markers = [...text.matchAll(/\bXRAY_[A-Z_]+\b/g)].map((match) => match[0]);
  const criticalMarkers = markers.filter((marker) => /NO_STATS|STALE_STATS|BLOCKED_SESSION|ALERT|MONITOR_ERROR/.test(marker));
  const errorCodes = [...new Set([...text.matchAll(/\bORA-\d{5}\b/gi)].map((match) => match[0].toUpperCase()))].slice(0, 20);
  const meaningfulLines = text.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !/^-+$/.test(line));
  const severity = errorCodes.length || criticalMarkers.length ? "HIGH" : markers.length ? "MEDIUM" : "INFO";
  const signals = markers.length + errorCodes.length;
  const headline = errorCodes.length ? `${errorCodes.length} Oracle error code${errorCodes.length === 1 ? "" : "s"} returned` : criticalMarkers.length ? `${criticalMarkers.length} priority signal${criticalMarkers.length === 1 ? "" : "s"} detected` : markers.length ? `${markers.length} review signal${markers.length === 1 ? "" : "s"} detected` : meaningfulLines.length ? "Evidence captured without an automatic risk marker" : "No current rows returned";
  return { severity, signals, markers: [...new Set(markers)].slice(0, 20), errorCodes, lines: meaningfulLines.length, headline, phase: definition.phase };
}
